# Generated by Django 5.2.7 on 2025-12-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercloud',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='owners', to='user.file'),
        ),
    ]
