# Generated by Django 5.1.5 on 2025-12-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usercloud_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercloud',
            name='files',
        ),
    ]
