# Generated by Django 5.2.7 on 2025-12-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usercloud_files'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usercloud',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='usercloud',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
